name: Release action
# Call the reusable workflow release-solution-with-inputs.yml
# Release your solution to prod when you create a new release.

on:
  release:
      types: [created]        
permissions:
  contents: write
jobs:
  Release-solution-ALMLab:
    uses: ./.github/workflows/release-solution-to-prod-with-inputs.yml
    with:
      #You can specify the solution name here
      solution_name: ALMLab
      #Update your values here
      BUILD_ENVIRONMENT_URL: https://org3f746ddb.crm11.dynamics.com/
      PRODUCTION_ENVIRONMENT_URL: https://org1cfdc6fb.crm11.dynamics.com/
      CLIENT_ID: 42ee8879-c979-4125-b435-102423da1a0c
      TENANT_ID: 539ad14d-5a3b-4b88-922e-a88c4ed0cddb   
    secrets:
      envSecret: ${{ secrets.PowerPlatformSPN }}
